title: Virginie Prints
baseurl: "/my-catalogue"
url: "https://xpac27.github.io"
collections_dir: "catalogues/virginie-prints-catalogue"
collections:
  products:
    output: false
include:
  - catalogues/virginie-prints-catalogue/_products
