title: Virginie Prints
baseurl: ""
url: "https://www.virginieprints.com"
collections_dir: "catalogues/virginie-prints-catalogue"
collections:
  products:
    output: true
    permalink: /products/:path/
defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: product
include:
  - catalogues/virginie-prints-catalogue/_products
